# Site
title: GTVR
motto: >
  Looking Into the Metaverse
description: >
  Georgia Tech Virtual Reality Club
email: contact@gtvr.club

# Social
github:   http://www.github.com/gtvr/
twitter:  http://www.twitter.com/gatechvr/
facebook: http://www.facebook.com/gtvr/

# Credentials
google_site_verification: ""
msvalidate:               ""