# Site
title: GTVR
motto: >
  Headsets and Dragons
description: >
  Georgia Tech Virtual Reality Club
email: contact@gtvr.club

# Social
github:   https://www.github.com/gtvr/
twitter:  https://twitter.com/gtvr_club/
facebook: https://www.facebook.com/groups/216670995372090/

# SEO Credentials
google_site_verification: ""
msvalidate:               ""