defaults:
    -
        scope:
            path: ""
			type: "site"
        values:
			title: "Georgia Tech Virtual Reality Club"
			title-min: "GT VR Club"
			motto: "Blurring the virtual and physical"
            layout: "default"