# Site
title: GTVR
motto: >
  Headsets and Dragons
description: >
  Georgia Tech Virtual Reality Club
email: m.rizvi@gatech.edu

# Social
github:   http://www.github.com/gtvr/
twitter:  http://www.twitter.com/gatechvr/
facebook: http://www.facebook.com/gtvr/

# SEO Credentials
google_site_verification: ""
msvalidate:               ""