# Site
title: VR@GT
motto: >
  Headsets and Dragons
description: >
  Virtual Reality Club @ Georgia Tech
email: contact@gtvr.club

# Social
github:   https://www.github.com/gtvr/
twitter:  https://twitter.com/VR_at_GT/
facebook: https://www.facebook.com/groups/216670995372090/

# SEO Credentials
google_site_verification: ""
msvalidate:               ""
